name: Compile typespec's file

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-compile-tsp
  cancel-in-progress: true

jobs:
  compile:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v5

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - run: npm ci

      - run: npm run build

      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: json-schema
          path: ./dist/@typespec/
